import {
  ExitQuestionIcon,
  FillInTheBlankView,
  QuestionContentCompactView,
  RadialProgress,
  SolutionModal,
} from "@/components/app/flashcard";
import { SubmitButton } from "@/components/shared";
import { checkAuthAsync } from "@/lib/auth/checkAuthAsync";
import { getMultipleChoiceQuestions } from "@/lib/chatgpt";
import {
  getOneAcceptedSubmission,
  getQuestionTitleAndContent,
} from "@/lib/leetcode";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

export default async function QuestionPage({
  searchParams,
}: {
  searchParams: { slug: string; ai: boolean };
}) {
  const supabase = createClient();

  const user = await checkAuthAsync(supabase);
  if (!user) {
    redirect("/login");
  }

  const progressValue = Math.floor(Math.random() * 101);
  const {
    questionContent,
    questionTitle,
    questionDifficulty,
    questionFrontendId,
  } = await getQuestionTitleAndContent(searchParams?.slug);

  //   const intuition = !!searchParams?.ai
  //     ? await getIntuition(searchParams?.slug)
  //     : "ChatGPT response does not load by default.";

  const multipleChoice = !!searchParams?.ai
    ? await getMultipleChoiceQuestions(searchParams?.slug)
    : null;

  const addAiToQueryParam = async () => {
    "use server";
    return redirect(`/chatgptexploration?slug=${searchParams?.slug}&ai=true`);
  };

  const { submissionDetails } = await getOneAcceptedSubmission(
    searchParams?.slug,
  );

  return (
    <div className="flex min-h-screen w-screen max-w-screen-lg flex-col">
      {/* Progress Bar */}
      <div className="flex w-full items-center justify-between p-4">
        <ExitQuestionIcon />
        <RadialProgress value={progressValue} />
      </div>

      {/* Question */}
      {!!questionContent &&
      !!questionTitle &&
      !!questionDifficulty &&
      !!questionFrontendId ? (
        <div className="flex w-full flex-col">
          <QuestionContentCompactView
            title={questionTitle}
            content={questionContent}
            difficulty={questionDifficulty}
            questionId={questionFrontendId}
          />
        </div>
      ) : (
        <div role="alert" className="alert alert-error">
          <span>Error -- Failed to retrieve data.</span>
        </div>
      )}

      {/* Answer */}
      <div className="flex w-full flex-1 flex-col p-4">
        <h1 className="mb-2 text-xl font-bold">Problem Intuition</h1>
        {/* <p>{intuition}</p> */}
        {!!multipleChoice && !!submissionDetails?.code ? (
          <FillInTheBlankView
            multipleChoice={multipleChoice}
            submissionCode={submissionDetails.code}
          />
        ) : (
          <p>ChatGPT Response not loaded by default.</p>
        )}
        <p className="mt-2 text-sm text-accent">
          Answers generated by AI may have inaccuracies.
        </p>
        <SolutionModal content={submissionDetails?.code} />
        <form>
          <SubmitButton
            formAction={addAiToQueryParam}
            pendingText="Generating..."
            className="btn btn-primary btn-block mt-4 rounded-xl"
          >
            Generate Response
          </SubmitButton>
        </form>
      </div>
    </div>
  );
}
