

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."GeneratedQuestions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "imported_questions_and_solutions_id" bigint,
    "source" "text",
    "source_id" "text",
    "data" "json",
    "version" bigint,
    "version_description" "text"
);


ALTER TABLE "public"."GeneratedQuestions" OWNER TO "postgres";


ALTER TABLE "public"."GeneratedQuestions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."GeneratedQuestions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ImportedQuestionsAndSolutions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "source" "text",
    "source_id" "text",
    "data" "json"
);


ALTER TABLE "public"."ImportedQuestionsAndSolutions" OWNER TO "postgres";


COMMENT ON TABLE "public"."ImportedQuestionsAndSolutions" IS 'Everything in one place';



ALTER TABLE "public"."ImportedQuestionsAndSolutions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ImportedQuestionsAndSolutions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."GeneratedQuestions"
    ADD CONSTRAINT "GeneratedQuestions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ImportedQuestionsAndSolutions"
    ADD CONSTRAINT "ImportedQuestionsAndSolutions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."GeneratedQuestions"
    ADD CONSTRAINT "GeneratedQuestions_imported_questions_and_solutions_id_fkey" FOREIGN KEY ("imported_questions_and_solutions_id") REFERENCES "public"."ImportedQuestionsAndSolutions"("id");



CREATE POLICY "Enable read access for all users" ON "public"."GeneratedQuestions" AS RESTRICTIVE FOR SELECT USING (true);



ALTER TABLE "public"."GeneratedQuestions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ImportedQuestionsAndSolutions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."GeneratedQuestions" TO "anon";
GRANT ALL ON TABLE "public"."GeneratedQuestions" TO "authenticated";
GRANT ALL ON TABLE "public"."GeneratedQuestions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."GeneratedQuestions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."GeneratedQuestions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."GeneratedQuestions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ImportedQuestionsAndSolutions" TO "anon";
GRANT ALL ON TABLE "public"."ImportedQuestionsAndSolutions" TO "authenticated";
GRANT ALL ON TABLE "public"."ImportedQuestionsAndSolutions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ImportedQuestionsAndSolutions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ImportedQuestionsAndSolutions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ImportedQuestionsAndSolutions_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
