name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies
        run: npm ci # Ensures clean install using package-lock.json

      - name: Run Lint
        run: npm run lint # Run linting if your project has it

      - name: Run Check Types
        run: npm run check-types # Check typescript types work

      - name: Run Prettier Check
        run: npm run prettier:check # Check prettier formatted well

      - name: Run Build
        run: npm run build # Ensures the project builds successfully
